/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package PaintImage;

import java.io.File;
import javax.sound.sampled.LineEvent;
import javax.sound.sampled.LineEvent.Type;
import javax.sound.sampled.LineListener;
import sm.sound.SMSoundPlayer;
/**
 *
 * @author ivan
 */


public class VentanaInternaPlayer extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaInternaPlayer
     */
    SMSoundPlayer player;
    
    
    public VentanaInternaPlayer(File audioFile) {
        initComponents();
        player = new SMSoundPlayer(audioFile);
        player.setLineListener(this.lineListener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    LineListener lineListener = new LineListener(){
        public void update(LineEvent event) {
            if(event.getType()==Type.START) {
                playButton.setIcon(new javax.swing.ImageIcon("/home/ivan/Dropbox/UNIVERSIDAD 2013-2014/SMM/PRACTICAS/PRACTICA11/PaintImage/src/iconosAudio/PlayDisabled_48x48.png"));
                stopButton.setIcon(new javax.swing.ImageIcon("/home/ivan/Dropbox/UNIVERSIDAD 2013-2014/SMM/PRACTICAS/PRACTICA11/PaintImage/src/iconosAudio/StopNormalRed_48x48.png"));
                playButton.setSelected(true);
            }
            if(event.getType()==Type.STOP) {
                stopButton.setSelected(true);
                playButton.setIcon(new javax.swing.ImageIcon("/home/ivan/Dropbox/UNIVERSIDAD 2013-2014/SMM/PRACTICAS/PRACTICA11/PaintImage/src/iconosAudio/PlayPressed_48x48.png"));
                stopButton.setIcon(new javax.swing.ImageIcon("/home/ivan/Dropbox/UNIVERSIDAD 2013-2014/SMM/PRACTICAS/PRACTICA11/PaintImage/src/iconosAudio/StopDisabled_48x48.png"));
            
            }
        }
    };
    
    
        


    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        playButton = new javax.swing.JToggleButton();
        stopButton = new javax.swing.JToggleButton();

        getContentPane().setLayout(new java.awt.GridLayout());

        buttonGroup.add(playButton);
        playButton.setIcon(new javax.swing.ImageIcon("/home/ivan/Dropbox/UNIVERSIDAD 2013-2014/SMM/PRACTICAS/PRACTICA11/PaintImage/src/iconosAudio/PlayPressed_48x48.png")); // NOI18N
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });
        getContentPane().add(playButton);

        buttonGroup.add(stopButton);
        stopButton.setIcon(new javax.swing.ImageIcon("/home/ivan/Dropbox/UNIVERSIDAD 2013-2014/SMM/PRACTICAS/PRACTICA11/PaintImage/src/iconosAudio/StopDisabled_48x48.png")); // NOI18N
        stopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopButtonActionPerformed(evt);
            }
        });
        getContentPane().add(stopButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButtonActionPerformed
        this.player.play();
    }//GEN-LAST:event_playButtonActionPerformed

    private void stopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopButtonActionPerformed
        this.player.stop();
    }//GEN-LAST:event_stopButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JToggleButton playButton;
    private javax.swing.JToggleButton stopButton;
    // End of variables declaration//GEN-END:variables
}
