/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package PaintImage;

import java.awt.Component;
import java.io.File;
import javax.media.Manager;
import javax.media.MediaLocator;
import javax.media.Player;

/**
 *
 * @author ivan
 */
public class VentanaInternaJMFPlayer extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaInternaJMFPlayer
     */
    Player p;
    
    private VentanaInternaJMFPlayer(File f) {
        initComponents();
        try { 
            MediaLocator ml = new MediaLocator("file:"+f.getAbsolutePath()); 
            this.p = Manager.createRealizedPlayer(ml); 
            Component areaVisual = this.p.getVisualComponent(); 
            if(areaVisual!=null) this.panelContPanel.add(areaVisual,java.awt.BorderLayout.CENTER);
            Component panelControl = this.p.getControlPanelComponent(); 
            if(panelControl!=null)  this.panelContPanel.add(panelControl,java.awt.BorderLayout.SOUTH);
        } catch(Exception e) {
            System.err.println("Error al abrir la ventana " + e.getLocalizedMessage());
        }
    }
    public static VentanaInternaJMFPlayer getInstance(File f){
            VentanaInternaJMFPlayer vijmf = new VentanaInternaJMFPlayer(f);
            if (vijmf!=null)
                return vijmf;
            else{
                return null;    
            }
   
    }
    public void play(){
        p.start();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContPanel = new javax.swing.JPanel();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setMinimumSize(new java.awt.Dimension(200, 200));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        panelContPanel.setMinimumSize(new java.awt.Dimension(200, 200));
        panelContPanel.setLayout(new java.awt.BorderLayout());
        getContentPane().add(panelContPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelContPanel;
    // End of variables declaration//GEN-END:variables
}
