
package PaintImage;

import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.List;
import javax.media.Buffer;
import javax.media.CannotRealizeException;
import javax.media.CaptureDeviceInfo;
import javax.media.CaptureDeviceManager;
import javax.media.Manager;
import javax.media.MediaLocator;
import javax.media.NoPlayerException;
import javax.media.Player;
import javax.media.control.FrameGrabbingControl;
import javax.media.format.VideoFormat;
import javax.media.format.YUVFormat;
import javax.media.util.BufferToImage;


/**
 * Ventana que contendrá la captura de la webcam.
 * Esta ventana visualizará la el flujo de imagen obtenido desde la webcam.
 * 
 * @author Ivan Ortega Alba
 */
public class VentanaInternaCamara extends javax.swing.JInternalFrame {

    /**
     * Reproductor
     */
    Player p;
    
    /**
     * Constructor por defecto, el cual asignará la webcam disponible como fuente,
     * y reproducirá las imagenes obtenidas en al ventana interna.
     * Como puede dar errores la apertura de flujo, hemos declarado privado el contructor,
     * y obtendremos el objeto mediante el método {@link VentanaInternaCamara.getInstance()}
     */
    public VentanaInternaCamara() {
        initComponents();
        try { 
            CaptureDeviceInfo deviceInfo; 
            List<CaptureDeviceInfo> deviceList = CaptureDeviceManager.getDeviceList(new YUVFormat()); 
            deviceInfo = deviceList.get(0); 
            MediaLocator ml = deviceInfo.getLocator(); 
            this.p = Manager.createRealizedPlayer(ml); 
            Component areaVisual = p.getVisualComponent(); 
            
            if(areaVisual!=null) this.add(areaVisual,BorderLayout.CENTER); 
                Component panelControl = p.getControlPanelComponent(); 
            if(panelControl!=null) 
                this.add(panelControl,BorderLayout.SOUTH); 
            
            } catch(IOException | CannotRealizeException | NoPlayerException e) {} 
    }
    /**
     * Se encarga de crear una instancia mediante el contructor de la clase.
     * 
     * @see VentanaInternaCamara()
     * @return devuelve una instancia de tipo {@link VentanaInternaCamara} 
     */
    static public VentanaInternaCamara getInstance(){
        VentanaInternaCamara vic = new VentanaInternaCamara();
        return vic!=null?vic:null;
        
    }
    /**
     * Realiza una captura de pantalla de la imagen en reproducción de la 
     * webcam y la almacena en un objeto de tipo {@link BufferedImage}.
     * 
     * @return imagen correspondiente a la captura de fotograma.
     */
    public BufferedImage getFrame(){ 
        FrameGrabbingControl fgc; 
        String claseCtr = "javax.media.control.FrameGrabbingControl "; 
        fgc = (FrameGrabbingControl)this.p.getControl(claseCtr); 
        Buffer bufferFrame = fgc.grabFrame(); 
        BufferToImage bti; 
        bti=new BufferToImage((VideoFormat)bufferFrame.getFormat()); 
        Image img = bti.createImage(bufferFrame); 
        return (BufferedImage)img; 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
